import { WorkTrack, WorkTracks } from '../net/WorkTrack'
@Extend(SymbolGlyph) function icon(){
  .fontSize(48)
  .fontWeight(FontWeight.Bold)
}

@Preview
@Component
export struct Files{
  @Require @Prop showList:WorkTracks = [
    {
      "type": "folder",
      "title": "01 通常版",
      "children": [
        {
          "type": "folder",
          "title": "WAV",
          "children": [
            {
              "type": "audio",
              "hash": "1204312/1076659",
              "title": "01 説明.wav",
              "work": {
                "id": 1204312,
                "source_id": "RJ01204312",
                "source_type": "DLSITE"
              },
              "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
              "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/01%20%E8%AA%AC%E6%98%8E.wav",
              "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/01%20%E8%AA%AC%E6%98%8E.wav",
              "streamLowQualityUrl": "https://fast.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/01%20%E8%AA%AC%E6%98%8E.m4a",
              "duration": 53,
              "size": 20357090
            },
            {
              "type": "audio",
              "hash": "1204312/1076660",
              "title": "02 まんこ屋でございます.wav",
              "work": {
                "id": 1204312,
                "source_id": "RJ01204312",
                "source_type": "DLSITE"
              },
              "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
              "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/02%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.wav",
              "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/02%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.wav",
              "streamLowQualityUrl": "https://fast.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/02%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.m4a",
              "duration": 548,
              "size": 210437090
            },
            {
              "type": "audio",
              "hash": "1204312/1076661",
              "title": "03 まんチョイスおまんこ挿入.wav",
              "work": {
                "id": 1204312,
                "source_id": "RJ01204312",
                "source_type": "DLSITE"
              },
              "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
              "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/03%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.wav",
              "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/03%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.wav",
              "streamLowQualityUrl": "https://fast.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/WAV/03%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.m4a",
              "duration": 1220.9062,
              "size": 468833098
            }
          ]
        },
        {
          "type": "audio",
          "hash": "1204312/1076656",
          "title": "01 説明.mp3",
          "work": {
            "id": 1204312,
            "source_id": "RJ01204312",
            "source_type": "DLSITE"
          },
          "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
          "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/01%20%E8%AA%AC%E6%98%8E.mp3",
          "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/01%20%E8%AA%AC%E6%98%8E.mp3",
          "streamLowQualityUrl": "",
          "duration": 53.028572,
          "size": 3293783
        },
        {
          "type": "audio",
          "hash": "1204312/1076657",
          "title": "02 まんこ屋でございます.mp3",
          "work": {
            "id": 1204312,
            "source_id": "RJ01204312",
            "source_type": "DLSITE"
          },
          "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
          "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/02%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.mp3",
          "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/02%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.mp3",
          "streamLowQualityUrl": "",
          "duration": 548.04895,
          "size": 23094600
        },
        {
          "type": "audio",
          "hash": "1204312/1076658",
          "title": "03 まんチョイスおまんこ挿入.mp3",
          "work": {
            "id": 1204312,
            "source_id": "RJ01204312",
            "source_type": "DLSITE"
          },
          "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
          "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/03%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.mp3",
          "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/01%20%E9%80%9A%E5%B8%B8%E7%89%88/03%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.mp3",
          "streamLowQualityUrl": "",
          "duration": 1220.9371,
          "size": 50010126
        }
      ]
    },
    {
      "type": "folder",
      "title": "02 アクメナビゲート無し版",
      "children": [
        {
          "type": "folder",
          "title": "WAV",
          "children": [
            {
              "type": "audio",
              "hash": "1204312/1076665",
              "title": "アクメナビ無し版01 説明.wav",
              "work": {
                "id": 1204312,
                "source_id": "RJ01204312",
                "source_type": "DLSITE"
              },
              "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
              "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8801%20%E8%AA%AC%E6%98%8E.wav",
              "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8801%20%E8%AA%AC%E6%98%8E.wav",
              "streamLowQualityUrl": "https://fast.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8801%20%E8%AA%AC%E6%98%8E.m4a",
              "duration": 53,
              "size": 20357090
            },
            {
              "type": "audio",
              "hash": "1204312/1076666",
              "title": "アクメナビ無し版02 まんこ屋でございます.wav",
              "work": {
                "id": 1204312,
                "source_id": "RJ01204312",
                "source_type": "DLSITE"
              },
              "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
              "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8802%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.wav",
              "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8802%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.wav",
              "streamLowQualityUrl": "https://fast.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8802%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.m4a",
              "duration": 548,
              "size": 210437090
            },
            {
              "type": "audio",
              "hash": "1204312/1076667",
              "title": "アクメナビ無し版03 まんチョイスおまんこ挿入.wav",
              "work": {
                "id": 1204312,
                "source_id": "RJ01204312",
                "source_type": "DLSITE"
              },
              "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
              "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8803%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.wav",
              "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8803%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.wav",
              "streamLowQualityUrl": "https://fast.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/WAV/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8803%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.m4a",
              "duration": 1220.9062,
              "size": 468833098
            }
          ]
        },
        {
          "type": "audio",
          "hash": "1204312/1076662",
          "title": "アクメナビ無し版01 説明.mp3",
          "work": {
            "id": 1204312,
            "source_id": "RJ01204312",
            "source_type": "DLSITE"
          },
          "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
          "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8801%20%E8%AA%AC%E6%98%8E.mp3",
          "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8801%20%E8%AA%AC%E6%98%8E.mp3",
          "streamLowQualityUrl": "",
          "duration": 53.028572,
          "size": 2122218
        },
        {
          "type": "audio",
          "hash": "1204312/1076663",
          "title": "アクメナビ無し版02 まんこ屋でございます.mp3",
          "work": {
            "id": 1204312,
            "source_id": "RJ01204312",
            "source_type": "DLSITE"
          },
          "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
          "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8802%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.mp3",
          "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8802%20%E3%81%BE%E3%82%93%E3%81%93%E5%B1%8B%E3%81%A7%E3%81%94%E3%81%96%E3%81%84%E3%81%BE%E3%81%99.mp3",
          "streamLowQualityUrl": "",
          "duration": 548.04895,
          "size": 21923035
        },
        {
          "type": "audio",
          "hash": "1204312/1076664",
          "title": "アクメナビ無し版03 まんチョイスおまんこ挿入.mp3",
          "work": {
            "id": 1204312,
            "source_id": "RJ01204312",
            "source_type": "DLSITE"
          },
          "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
          "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8803%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.mp3",
          "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/02%20%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E3%82%B2%E3%83%BC%E3%83%88%E7%84%A1%E3%81%97%E7%89%88/%E3%82%A2%E3%82%AF%E3%83%A1%E3%83%8A%E3%83%93%E7%84%A1%E3%81%97%E7%89%8803%20%E3%81%BE%E3%82%93%E3%83%81%E3%83%A7%E3%82%A4%E3%82%B9%E3%81%8A%E3%81%BE%E3%82%93%E3%81%93%E6%8C%BF%E5%85%A5.mp3",
          "streamLowQualityUrl": "",
          "duration": 1220.9371,
          "size": 48838561
        }
      ]
    },
    {
      "type": "image",
      "hash": "1204312/1076651",
      "title": "Artwork01.jpg",
      "work": {
        "id": 1204312,
        "source_id": "RJ01204312",
        "source_type": "DLSITE"
      },
      "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
      "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/Artwork01.jpg",
      "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/Artwork01.jpg",
      "size": 1161323
    },
    {
      "type": "image",
      "hash": "1204312/1076652",
      "title": "Artwork02.jpg",
      "work": {
        "id": 1204312,
        "source_id": "RJ01204312",
        "source_type": "DLSITE"
      },
      "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
      "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/Artwork02.jpg",
      "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/Artwork02.jpg",
      "size": 888794
    },
    {
      "type": "image",
      "hash": "1204312/1076653",
      "title": "Artwork03.jpg",
      "work": {
        "id": 1204312,
        "source_id": "RJ01204312",
        "source_type": "DLSITE"
      },
      "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
      "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/Artwork03.jpg",
      "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/Artwork03.jpg",
      "size": 698130
    },
    {
      "type": "image",
      "hash": "1204312/1076654",
      "title": "ロゴ無しイラスト.jpg",
      "work": {
        "id": 1204312,
        "source_id": "RJ01204312",
        "source_type": "DLSITE"
      },
      "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
      "mediaStreamUrl": "https://raw.kiko-play-niptan.one/media/stream/daily/2024-06-29/RJ01204312/%E3%83%AD%E3%82%B4%E7%84%A1%E3%81%97%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88.jpg",
      "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/%E3%83%AD%E3%82%B4%E7%84%A1%E3%81%97%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88.jpg",
      "size": 1628627
    },
    {
      "type": "text",
      "hash": "1204312/1076655",
      "title": "説明書.txt",
      "work": {
        "id": 1204312,
        "source_id": "RJ01204312",
        "source_type": "DLSITE"
      },
      "workTitle": "【我慢イキ】まんこ屋本舗★まんチョイス#02「ふみか21歳のおまんこ」〜当店は女性のアクメは禁止のおまんこ貸し出しサービスです〜【アクメナビ搭載】",
      "mediaStreamUrl": "https://api.asmr-200.com/api/media/stream/1204312/1076655",
      "mediaDownloadUrl": "https://raw.kiko-play-niptan.one/media/download/daily/2024-06-29/RJ01204312/%E8%AA%AC%E6%98%8E%E6%9B%B8.txt",
      "size": 2499
    }
  ]
  @State selectIndex:number = -1

  @Require @Prop stackList:Array<WorkTracks> = []
  //显示层级
  @State level:number = 0
  aboutToAppear(): void {
    // this.stackList.push(this.showList)
  }

  build(){
    Column(){
      Stack(){
        Repeat<WorkTracks>(this.stackList).each((stackList)=>{
          List({space:10}){
            ListItemGroup(){
              ListItem(){
                this.GoBackFolder()
              }
            }
            Repeat<WorkTrack>(stackList.item).each(workTracks=>{
              ListItem(){
                if (workTracks.item.type ==='folder') {
                  this.Folder(workTracks.item)
                }else{
                  this.File(workTracks.item,workTracks.index||0)
                }
              }.swipeAction({
                end:this.download()
              })
            }).key((item,index)=>item.title+index)
          }.divider({
            strokeWidth: 0.5,
            color: Color.Gray,
            startMargin: 48,
            endMargin: 8
          })
          .backgroundColor(Color.Gray)
          .sticky(StickyStyle.Header)
          .width('100%')
          .height('100%')
        }).key((item,index)=>index+'')
      }.width('100%')
      .height('100%')
      .alignContent(Alignment.Top)
    }
    .padding({
      top: 8,
      bottom:8,
      left: 16,
      right: 16
    })
    .margin({ top:8 })
    .backgroundColor(Color.White)
    .borderRadius(24)
  }
  @Builder GoBackFolder(){
    if (this.stackList.length>1){
      Row({space:16}){
        SymbolGlyph($r('sys.symbol.undo')).icon()
        Text('返回上一级...')
      }
      .fileRow()
      .onClick(()=>{
        //返回上一层及
        if (this.stackList.length>1){
          this.stackList.pop()
        }
      })
    }
  }
  @Builder Folder(track:WorkTrack){
    Row({space:16}){
      if (track.children && track.children?.length>0){
        SymbolGlyph($r('sys.symbol.folder_fill')).icon().fontColor([Color.Orange])
      }else{
        SymbolGlyph($r('sys.symbol.folder')).icon().fontColor([Color.Orange])
      }
      Text(track.title)
        .fontSize(16)
        .fontColor('#FF182431')
        .maxLines(1)
        .textOverflow({
          overflow: TextOverflow.Ellipsis
        })
    }
    .fileRow()
    .onClick(()=>{
      //进入下一层级
      console.log("onClick")
      if (track.children && track.children?.length>0) {
        this.stackList.push(track.children);
      }
    })
  }
  @Builder File(track:WorkTrack,index:number){
    Row(){
      Stack(){
        Row({space:16}){
          if (track.type === 'audio'){
            SymbolGlyph($r('sys.symbol.music')).icon().fontColor([Color.Green])
          }else if (track.type === 'text'){
            SymbolGlyph($r('sys.symbol.doc_text')).icon().fontColor([Color.Gray])
          }else if (track.type === 'image'){
            SymbolGlyph($r('sys.symbol.picture')).icon().fontColor([Color.Blue])
          }else{
            SymbolGlyph($r('sys.symbol.doc')).icon().fontColor([Color.Gray])
          }
          Text(track.title)
            .fontSize(16)
            .fontColor('#FF182431')
            .maxLines(1)
            .textOverflow({
              overflow: TextOverflow.Ellipsis
            })
        }.width('100%')
      }.layoutWeight(1)
      .height(48)
    }
  }

  //文件行样式
  @Styles fileRow(){
    .width('100%')
    .height(60)
  }

  @Builder download(){
    Button('下载').type(ButtonType.Circle)
      .onClick(()=>{
        console.log('下载')
      })
  }
}